# Generated by Django 6.0 on 2025-12-17 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('horas_trabajadas', models.FloatField(default=0, verbose_name='Horas Trabajadas')),
                ('reconocimiento_facial', models.BooleanField(default=False, verbose_name='Reconocimiento Facial')),
                ('foto_registro', models.ImageField(blank=True, null=True, upload_to='asistencias/', verbose_name='Foto de Registro')),
                ('confianza_reconocimiento', models.FloatField(blank=True, help_text='Porcentaje de confianza del reconocimiento facial', null=True, verbose_name='Confianza del Reconocimiento')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('retardo', models.BooleanField(default=False, verbose_name='Retardo')),
                ('justificado', models.BooleanField(default=False, verbose_name='Justificado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='empleados.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
