# Generated by Django 6.0 on 2026-01-26 23:00

import checador.storage_backends
import registros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='descripcion_incidencia',
            field=models.TextField(blank=True, verbose_name='Descripción de Incidencia'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='hora_entrada_comida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada de Comida'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='hora_salida_comida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida a Comida'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='incidencia',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('registro_incompleto', 'Registro Incompleto'), ('sin_entrada_comida', 'Falta entrada de comida'), ('sin_salida_comida', 'Falta salida de comida'), ('sin_salida', 'Falta salida final')], default='ninguna', max_length=50, verbose_name='Incidencia'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(default=registros.models.fecha_mexico, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='foto_registro',
            field=models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='asistencias/', verbose_name='Foto de Registro'),
        ),
    ]
