# Generated by Django 6.0 on 2026-01-27 00:09

import checador.storage_backends
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_departamento_obj_and_more'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('requiere_autorizacion', models.BooleanField(default=True, verbose_name='Requiere Autorizacion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivo de Visita',
                'verbose_name_plural': 'Motivos de Visita',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_visita', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Codigo de Visita')),
                ('nombre_visitante', models.CharField(max_length=200, verbose_name='Nombre del Visitante')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('identificacion_tipo', models.CharField(choices=[('ine', 'INE/IFE'), ('pasaporte', 'Pasaporte'), ('licencia', 'Licencia de Conducir'), ('otro', 'Otro')], default='ine', max_length=20, verbose_name='Tipo de Identificacion')),
                ('identificacion_numero', models.CharField(blank=True, max_length=50, verbose_name='Numero de Identificacion')),
                ('foto_visitante', models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='visitas/fotos/', verbose_name='Foto del Visitante')),
                ('descripcion_motivo', models.TextField(blank=True, verbose_name='Descripcion del Motivo')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('hora_programada', models.TimeField(verbose_name='Hora Programada')),
                ('duracion_estimada', models.IntegerField(default=60, verbose_name='Duracion Estimada (minutos)')),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Salida')),
                ('codigo_qr', models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='visitas/qr/', verbose_name='Codigo QR')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('en_sitio', 'En Sitio'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('no_show', 'No Se Presento')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorizacion')),
                ('comentarios_autorizacion', models.TextField(blank=True, verbose_name='Comentarios de Autorizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_autorizadas', to='empleados.empleado', verbose_name='Autorizado Por')),
                ('departamento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='organizacion.departamento', verbose_name='Departamento Destino')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='visitas.motivovisita', verbose_name='Motivo')),
                ('persona_a_visitar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_recibidas', to='empleados.empleado', verbose_name='Persona a Visitar')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_programada', '-hora_programada'],
            },
        ),
    ]
