# Generated by Django 6.0 on 2026-01-27 17:26

import checador.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='persona_a_visitar',
        ),
        migrations.AddField(
            model_name='visita',
            name='foto_identificacion',
            field=models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='visitas/identificaciones/', verbose_name='Foto de Identificacion'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.TextField(verbose_name='Motivo de Visita'),
        ),
    ]
