# Generated by Django 6.0 on 2026-01-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_remove_visita_persona_a_visitar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='descripcion_motivo',
        ),
    ]
