# Generated by Django 6.0 on 2025-12-17 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, verbose_name='Código de Empleado')),
                ('foto_rostro', models.ImageField(blank=True, null=True, upload_to='rostros/', verbose_name='Foto de Rostro')),
                ('embedding_rostro', models.BinaryField(blank=True, null=True, verbose_name='Encoding Facial')),
                ('horas_semana', models.IntegerField(default=40, verbose_name='Horas por Semana')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('puesto', models.CharField(blank=True, max_length=100, verbose_name='Puesto')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['codigo_empleado'],
            },
        ),
    ]
