# Generated by Django 6.0 on 2026-01-27 00:09

import checador.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='organizacion.departamento', verbose_name='Departamento (Estructura)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='supervisor_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='empleados.empleado', verbose_name='Supervisor Directo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='rostros/', verbose_name='Foto de Rostro'),
        ),
    ]
