# Generated by Django 6.0 on 2026-01-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_departamento_obj_and_more'),
        ('horarios', '0003_tipohorario_asignacionhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horario_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_predeterminados', to='horarios.tipohorario', verbose_name='Horario Predeterminado'),
        ),
    ]
