# Generated by Django 6.0 on 2026-02-07 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_horario_predeterminado'),
        ('horarios', '0003_tipohorario_asignacionhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='descansa_domingo',
            field=models.BooleanField(default=True, help_text='Si está marcado, el empleado descansa los domingos', verbose_name='Descansa Domingo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='descansa_sabado',
            field=models.BooleanField(default=False, help_text='Si está marcado, el empleado descansa los sábados', verbose_name='Descansa Sábado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_domingo',
            field=models.ForeignKey(blank=True, help_text='Horario que aplica los domingos (dejar vacío si descansa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_domingo', to='horarios.tipohorario', verbose_name='Horario Domingo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_sabado',
            field=models.ForeignKey(blank=True, help_text='Horario que aplica los sábados (dejar vacío si descansa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_sabado', to='horarios.tipohorario', verbose_name='Horario Sábado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horario_predeterminado',
            field=models.ForeignKey(blank=True, help_text='Horario que aplica de lunes a viernes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_predeterminados', to='horarios.tipohorario', verbose_name='Horario Lunes a Viernes'),
        ),
    ]
