# Generated by Django 6.0 on 2026-09-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_descansa_domingo_empleado_descansa_sabado_and_more'),
        ('organizacion', '0002_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organizacion.empresa', verbose_name='Empresa'),
        ),
    ]
