# Generated by Django 6.0 on 2026-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoequipo',
            name='actividades_realizadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de actividades realizadas durante el mantenimiento', verbose_name='Actividades Realizadas'),
        ),
    ]
