# Generated by Django 6.0 on 2026-01-29 18:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal')], max_length=20, unique=True, verbose_name='Tipo de Reporte')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('hora_envio', models.TimeField(default=datetime.time(11, 50), verbose_name='Hora de envio')),
                ('asunto_email', models.CharField(blank=True, help_text='Dejar vacio para usar asunto por defecto', max_length=255, verbose_name='Asunto del email')),
                ('dia_envio_semanal', models.IntegerField(blank=True, choices=[(5, 'Viernes'), (6, 'Sabado')], help_text='Solo aplica para reporte semanal', null=True, verbose_name='Dia de envio (semanal)')),
                ('incluir_excel', models.BooleanField(default=False, help_text='El reporte diario no incluye Excel por defecto', verbose_name='Incluir anexo Excel')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='LogReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=20, verbose_name='Tipo')),
                ('fecha_inicio_rango', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin_rango', models.DateField(verbose_name='Fecha fin')),
                ('destinatarios_enviados', models.IntegerField(default=0, verbose_name='Destinatarios')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error'), ('parcial', 'Parcial')], max_length=20, verbose_name='Estado')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle de error')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
            options={
                'verbose_name': 'Log de Reporte',
                'verbose_name_plural': 'Logs de Reportes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='reportes.configuracionreporte')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'unique_together': {('configuracion', 'email')},
            },
        ),
    ]
