# Generated by Django 6.0 on 2026-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('inventario', 'Inventario de Equipos'), ('tickets_it', 'Tickets IT'), ('permisos', 'Permisos Laborales')], max_length=20, unique=True, verbose_name='Tipo de Reporte'),
        ),
    ]
