# Generated by Django 6.0 on 2026-09-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_empresa'),
        ('reportes', '0002_nuevos_tipos_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreporte',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para diario/semanal/quincenal. Debe quedar vacío para inventario/tickets_it/permisos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_reporte', to='organizacion.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='logreporte',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_reporte', to='organizacion.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('inventario', 'Inventario de Equipos'), ('tickets_it', 'Tickets IT'), ('permisos', 'Permisos Laborales')], max_length=20, verbose_name='Tipo de Reporte'),
        ),
        migrations.AddConstraint(
            model_name='configuracionreporte',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('tipo',), name='config_reporte_unico_sin_empresa'),
        ),
        migrations.AddConstraint(
            model_name='configuracionreporte',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('tipo', 'empresa'), name='config_reporte_unico_por_empresa'),
        ),
    ]
