# Generated by Django 6.0 on 2026-01-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartamentos', to='organizacion.departamento', verbose_name='Departamento Padre')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to='empleados.empleado', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('directa', 'Directa'), ('funcional', 'Funcional'), ('temporal', 'Temporal')], default='directa', max_length=20, verbose_name='Tipo de Relacion')),
                ('puede_autorizar_permisos', models.BooleanField(default=True, verbose_name='Puede Autorizar Permisos')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('subordinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores_relaciones', to='empleados.empleado', verbose_name='Subordinado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinados_relaciones', to='empleados.empleado', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Relacion de Supervision',
                'verbose_name_plural': 'Relaciones de Supervision',
                'ordering': ['supervisor', 'subordinado'],
                'unique_together': {('supervisor', 'subordinado', 'tipo_relacion')},
            },
        ),
    ]
