# Generated by Django 6.0 on 2025-12-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('tolerancia_minutos', models.IntegerField(default=10, help_text='Minutos de tolerancia para entrada', verbose_name='Tolerancia (minutos)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='empleados.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['empleado', 'dia_semana'],
                'unique_together': {('empleado', 'dia_semana')},
            },
        ),
    ]
