# Generated by Django 6.0 on 2026-01-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='hora_fin_comida',
            field=models.TimeField(blank=True, help_text='Hora límite para regresar de comer (ej: 16:00)', null=True, verbose_name='Hora fin de comida'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio_comida',
            field=models.TimeField(blank=True, help_text='Hora a partir de la cual puede salir a comer (ej: 13:00)', null=True, verbose_name='Hora inicio de comida'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tiene_comida',
            field=models.BooleanField(default=True, help_text='Indica si el empleado tiene periodo de comida', verbose_name='Tiene horario de comida'),
        ),
    ]
