# Generated by Django 6.0 on 2026-01-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_departamento_obj_and_more'),
        ('horarios', '0002_horario_hora_fin_comida_horario_hora_inicio_comida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('color', models.CharField(default='#3B82F6', help_text='Color para identificar el horario en la vista de asignacion', max_length=7, verbose_name='Color (hex)')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('tolerancia_minutos', models.IntegerField(default=10, help_text='Minutos de tolerancia para entrada', verbose_name='Tolerancia (minutos)')),
                ('tiene_comida', models.BooleanField(default=True, verbose_name='Tiene comida')),
                ('hora_inicio_comida', models.TimeField(blank=True, null=True, verbose_name='Hora inicio comida')),
                ('hora_fin_comida', models.TimeField(blank=True, null=True, verbose_name='Hora fin comida')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Horario',
                'verbose_name_plural': 'Tipos de Horario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_horario', to='empleados.empleado', verbose_name='Empleado')),
                ('tipo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horarios.tipohorario', verbose_name='Tipo de Horario')),
            ],
            options={
                'verbose_name': 'Asignacion de Horario',
                'verbose_name_plural': 'Asignaciones de Horario',
                'indexes': [models.Index(fields=['fecha'], name='horarios_as_fecha_77169e_idx'), models.Index(fields=['empleado', 'fecha'], name='horarios_as_emplead_6acd67_idx')],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
