# Generated by Django 6.0 on 2026-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_tipohorario_asignacionhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohorario',
            name='cruza_medianoche',
            field=models.BooleanField(default=False, help_text='Activar si la salida ocurre al día siguiente (ej. turno 21:00 - 7:00)', verbose_name='Cruza medianoche'),
        ),
    ]
