# Generated by Django 6.0 on 2026-01-27 00:09

import checador.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_departamento_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('requiere_evidencia', models.BooleanField(default=False, verbose_name='Requiere Evidencia')),
                ('dias_maximos', models.IntegerField(blank=True, null=True, verbose_name='Dias Maximos')),
                ('dias_anticipacion', models.IntegerField(default=1, verbose_name='Dias de Anticipacion Requeridos')),
                ('afecta_salario', models.BooleanField(default=True, verbose_name='Con Goce de Sueldo')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color (hex)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Permiso',
                'verbose_name_plural': 'Tipos de Permiso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('evidencia', models.FileField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='permisos/evidencias/', verbose_name='Evidencia')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolucion')),
                ('comentarios_resolucion', models.TextField(blank=True, verbose_name='Comentarios de Resolucion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to='empleados.empleado', verbose_name='Aprobador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permiso', to='empleados.empleado', verbose_name='Empleado')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='permisos.tipopermiso', verbose_name='Tipo de Permiso')),
            ],
            options={
                'verbose_name': 'Solicitud de Permiso',
                'verbose_name_plural': 'Solicitudes de Permiso',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('modificado', 'Modificado')], max_length=20, verbose_name='Accion')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado', verbose_name='Usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='permisos.solicitudpermiso', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial de Permiso',
                'verbose_name_plural': 'Historial de Permisos',
                'ordering': ['-fecha'],
            },
        ),
    ]
